export const projectConstant = [
  {
    id: 1,
    title: "BisLingo",
    imgSrc: "./images/bislingo.png",
    previewLink: " ./project/bislingo",
    codeLink: "hhttps://github.com/OzanOcak/BisLingo",
    technology: "reactnative",
    tags: ["React Native", "Android", "JavaScript"],
    description: "Android Application ",
  },

  {
    id: 2,
    title: "Clinic Home Page",
    imgSrc: "./images/uiux03.png",
    previewLink: "https://quiet-souffle-ebc9e0.netlify.app/",
    codeLink: "https://github.com/OzanOcak/react-health-clinic",
    technology: "ui",
    tags: ["CSS", "react.js", "tailwind CSS"],
    description: "modern landing page design with react.js and tailwind CSS",
  },

  {
    id: 3,
    title: "Tim Burton Website",
    imgSrc: "./images/css01.png",
    previewLink: "https://jocular-tarsier-34cb74.netlify.app/",
    codeLink: "https://github.com/OzanOcak/tim_butrton_fan_page",
    technology: "ui",
    tags: ["CSS", "react.js", "CSS"],
    description: "React app designed with Tailwind CSS",
  },
  {
    id: 4,
    title: "Twitter Clone",
    imgSrc: "./images/react05.png",
    previewLink: "https://twitterfirebaseclone.vercel.app/",
    codeLink: "https://github.com/OzanOcak/twitterfirebaseclone",
    technology: "reactjs",
    tags: ["Next.js", "react.js", "API"],
    description: "React app build up with Next.js",
  },
  {
    id: 5,
    title: "Medium Clone",
    imgSrc: "./images/react02.png",
    previewLink: "https://medium-sanity-clone-taupe.vercel.app/",
    codeLink: "https://github.com/OzanOcak/medium-sanity-clone",
    technology: "reactjs",
    tags: ["react.js", "API"],
    description: "React app build up with Next.js",
  },
  {
    id: 6,
    title: "Movie App",
    imgSrc: "./images/react03.png",
    previewLink: "https://radiant-bonbon-187868.netlify.app/",
    codeLink: "https://github.com/OzanOcak/book_repo",
    technology: "reactjs",
    tags: ["react.js", "API", "Node.js"],
    description: "MERN stack Movie App",
  },
  {
    id: 7,
    title: "March of Dimes Canada",
    imgSrc: "./images/marchofdimes.png",
    previewLink: "https://www.marchofdimes.ca/",
    technology: "javascript",
    tags: ["HTML", "CSS", "JavaScript"],
    description: "Clientsite website, custom theme",
  },
  {
    id: 8,
    title: "MODC Employment Service",
    imgSrc: "./images/modcemployment.png",
    previewLink: "https://www.modcemploymentservices.ca/",
    technology: "javascript",
    tags: ["HTML", "CSS", "JavaScript", "PHP", "WordPress"],
    description: "Clientsite website, custom theme",
  },
  {
    id: 9,
    title: "Drawring comics with css",
    imgSrc: "./images/comic1.png",
    previewLink: "https://www.oocak.com/comicswithcss",
    technology: "css",
    tags: ["HTML", "CSS"],
    description: "html, css",
  },
];

{
  /*export const projectConstant = [
  {
    id: 1,
    title: "Tiny Portfolio",
    imgSrc: "/images/uiux01.png",
    previewLink: " https://harmonious-parfait-b7b1a2.netlify.app/",
    codeLink: "https://github.com/OzanOcak/tinyPortfolio",
    technology: "css",
    tags: ["CSS", "react.js", "tailwind CSS"],
    description: "modern landing page design with react.js and tailwind CSS ",
  },
  {
    id: 2,
    title: "Cafe Corcellet",
    imgSrc: "/images/uiux02.png",
    previewLink: "https://harmonious-parfait-b7b1a2.netlify.app/",
    codeLink: "https://github.com/OzanOcak/cafeproust",
    technology: "css",
    tags: ["CSS", "react.js", "tailwind CSS"],
    description: "modern landing page design with react.js and tailwind CSS",
  },
  {
    id: 3,
    title: "Clinic Home Page",
    imgSrc: "./images/uiux03.png",
    previewLink: "https://quiet-souffle-ebc9e0.netlify.app/",
    codeLink: "https://github.com/OzanOcak/react-health-clinic",
    technology: "css",
    tags: ["CSS", "react.js", "tailwind CSS"],
    description: "modern landing page design with react.js and tailwind CSS",
  },
  {
    id: 4,
    title: "React Dictionary",
    imgSrc: "./images/react01.png",
    previewLink: "https://boisterous-capybara-189ef3.netlify.app/",
    codeLink: "https://github.com/OzanOcak/react-std-blog",
    technology: "reactjs",
    tags: ["CSS", "react.js", "tailwind CSS"],
    description: "React app with local storage",
  },
  {
    id: 5,
    title: "Tim Burton Website",
    imgSrc: "./images/css01.png",
    previewLink: "https://jocular-tarsier-34cb74.netlify.app/",
    codeLink: "https://github.com/OzanOcak/tim_butrton_fan_page",
    technology: "css",
    tags: ["CSS", "react.js", "CSS"],
    description: "React app designed with Tailwind CSS",
  },
  {
    id: 6,
    title: "Twitter Clone",
    imgSrc: "./images/react05.png",
    previewLink: "https://twitterfirebaseclone.vercel.app/",
    codeLink: "https://github.com/OzanOcak/twitterfirebaseclone",
    technology: "reactjs",
    tags: ["Next.js", "react.js", "API"],
    description: "React app build up with Next.js",
  },
  {
    id: 7,
    title: "Medium Clone",
    imgSrc: "./images/react02.png",
    previewLink: "https://medium-sanity-clone-taupe.vercel.app/",
    codeLink: "https://github.com/OzanOcak/medium-sanity-clone",
    technology: "reactjs",
    tags: ["react.js", "API"],
    description: "React app build up with Next.js",
  },
  {
    id: 8,
    title: "Movie App",
    imgSrc: "./images/react03.png",
    previewLink: "https://radiant-bonbon-187868.netlify.app/",
    codeLink: "https://github.com/OzanOcak/book_repo",
    technology: "reactjs",
    tags: ["react.js", "API", "Node.js"],
    description: "MERN stack Movie App",
  },
  {
    id: 9,
    title: "March of Dimes Canada",
    imgSrc: "./images/marchofdimes.png",
    previewLink: "https://www.marchofdimes.ca/",
    technology: "javascript",
    tags: ["HTML", "CSS", "JavaScript"],
    description: "Clientsite website, custom theme",
  },
  {
    id: 10,
    title: "MODC Employment Service",
    imgSrc: "./images/modcemployment.png",
    previewLink: "https://www.modcemploymentservices.ca/",
    technology: "javascript",
    tags: ["HTML", "CSS", "JavaScript", "PHP", "WordPress"],
    description: "Clientsite website, custom theme",
  },
];*/
}
